import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import ServiceAreaLinks from "@/components/ServiceAreaLinks";

export const metadata: Metadata = {
  title: "Impact Doors Fort Lauderdale | Hurricane-Rated Sliding Glass, French & Entry Doors",
  description:
    "Premium impact door installation in Fort Lauderdale, Broward & Palm Beach County. Hurricane-rated sliding glass doors, French doors, entry doors & patio doors. Free estimates. Call (754) 600-4876.",
  alternates: { canonical: "/services/impact-doors/" },
};

const benefits = [
  {
    icon: "🌀",
    title: "Category 5 Wind Resistance",
    description:
      "Every impact door we install is tested and certified to resist wind pressures generated by Category 5 hurricanes, meeting the strict Miami-Dade HVHZ requirements for large missile impact.",
  },
  {
    icon: "🏠",
    title: "Enhanced Curb Appeal",
    description:
      "Modern impact doors transform your home's appearance with sleek profiles, expansive glass, and premium hardware. Choose from contemporary, traditional, and coastal-inspired designs for your South Florida property.",
  },
  {
    icon: "💡",
    title: "Natural Light Maximization",
    description:
      "Impact sliding glass and French doors flood your interiors with South Florida sunshine while blocking heat and UV rays. Enjoy bright, open living spaces without compromising on protection.",
  },
  {
    icon: "🌡️",
    title: "Thermal Insulation",
    description:
      "Impact doors with Low-E glass and insulated frames significantly reduce heat transfer, keeping your home cooler in the summer and lowering monthly air conditioning costs across South Florida.",
  },
  {
    icon: "🔐",
    title: "Multi-Point Locking Security",
    description:
      "Our impact doors feature advanced multi-point locking systems that secure the door at multiple locations along the frame, providing superior resistance to forced entry and wind pressure.",
  },
  {
    icon: "📋",
    title: "Full Code Compliance",
    description:
      "All impact doors meet or exceed Florida Building Code, Miami-Dade County NOA approvals, and Broward County product approvals. We handle every permit and inspection for your project.",
  },
];

const doorTypes = [
  { name: "Sliding Glass Doors", href: "/services/door-types/sliding-glass/" },
  { name: "French Doors", href: "/services/door-types/french/" },
  { name: "Entry Doors", href: "/services/door-types/entry/" },
  { name: "Patio Doors", href: "/services/door-types/patio/" },
  { name: "Pivot Doors", href: "/services/door-types/pivot/" },
  { name: "Garage Impact Doors", href: "/services/door-types/garage/" },
];

const faqs = [
  {
    question: "What types of impact doors are available for South Florida homes?",
    answer:
      "We install a full range of impact-rated doors including sliding glass doors, French doors, front entry doors, patio doors, pivot doors, and garage impact doors. Each type is available in multiple styles, colors, and finishes to complement your home's architecture. Sliding glass impact doors are the most popular choice in South Florida due to the region's indoor-outdoor lifestyle and waterfront living.",
  },
  {
    question: "How much do impact doors cost in Miami and South Florida?",
    answer:
      "Impact door pricing depends on the type, size, glass options, and hardware selected. Standard impact sliding glass doors typically range from $1,500 to $4,000 installed, while premium entry doors with decorative glass can range from $2,000 to $6,000. French impact doors generally cost between $2,500 and $5,500. We provide free in-home estimates with detailed pricing and offer flexible financing options.",
  },
  {
    question: "Can I replace my regular sliding glass door with an impact sliding door?",
    answer:
      "Yes. Impact sliding glass door replacement is one of the most common upgrades we perform in South Florida. In most cases, a new impact sliding door can be installed into the existing opening with minimal modifications to the surrounding wall or frame. Our team handles the removal, installation, waterproofing, and finishing in a single visit, typically completing the work in half a day per door.",
  },
  {
    question: "Do impact doors qualify for insurance discounts in Florida?",
    answer:
      "Absolutely. Impact-rated doors are a key component of a whole-home hurricane mitigation system. When all openings including windows, doors, and the garage door are protected with impact-rated products, South Florida homeowners qualify for the maximum wind mitigation discount on their insurance premiums, which can save 20% to 45% or more annually.",
  },
  {
    question: "What is the difference between impact glass doors and standard doors with shutters?",
    answer:
      "Impact glass doors are engineered with laminated glass and reinforced frames that provide permanent hurricane protection without any preparation. Standard doors with shutters require manual deployment before each storm, can be difficult to operate, and provide no daily benefits. Impact doors additionally offer year-round noise reduction, UV protection, energy savings, and security.",
  },
];

export default function ImpactDoorsPage() {
  return (
    <>
      {/* Hero Section */}
      <section className="relative min-h-[60vh] flex items-center bg-ocean-950 overflow-hidden">
        <div className="absolute inset-0 bg-grid opacity-40" />
        <div className="absolute inset-0 mesh-gradient" />
        <div className="absolute top-20 right-10 w-96 h-96 bg-ocean-500/10 rounded-full blur-3xl animate-pulse-glow" />
        <div className="absolute bottom-20 left-10 w-80 h-80 bg-palm-500/10 rounded-full blur-3xl animate-pulse-glow" style={{ animationDelay: "1.5s" }} />

        <div className="relative z-10 max-w-7xl mx-auto px-4 py-20 lg:py-28">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
            <div className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-sm border border-white/10 rounded-full px-4 py-1.5 mb-6">
              <span className="w-2 h-2 bg-palm-400 rounded-full animate-pulse" />
              <span className="text-sm text-palm-300 font-medium">Hurricane-Rated Impact Doors</span>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold font-display text-white leading-tight mb-6">
              Premium <span className="gradient-text">Impact Doors</span> for South Florida Living
            </h1>
            <p className="text-lg text-gray-300 mb-8 max-w-xl leading-relaxed">
              Sliding glass, French, entry, and patio impact doors built to withstand Category 5 hurricanes. Beautiful designs that protect your family while enhancing your home across Miami-Dade, Broward, and Palm Beach County.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                href="/get-estimate/"
                className="inline-flex items-center justify-center gap-2 bg-gradient-to-r from-palm-500 to-palm-600 text-white px-8 py-4 rounded-full font-bold text-lg hover:from-palm-600 hover:to-palm-700 transition-all shadow-lg shadow-palm-500/25 hover:shadow-palm-500/40 hover:scale-105"
              >
                Get Free Estimate
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" /></svg>
              </Link>
              <a
                href="tel:+17546004876"
                className="inline-flex items-center justify-center gap-2 bg-white/10 backdrop-blur-sm border border-white/20 text-white px-8 py-4 rounded-full font-bold text-lg hover:bg-white/20 transition-all"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" /></svg>
                (754) 600-4876
              </a>
            </div>
            </div>
            <div>
              <div className="relative rounded-3xl overflow-hidden shadow-2xl shadow-black/30 border border-white/10">
                <Image
                  src="/images/imapct doors.jpg"
                  alt="Premium impact doors installed on a South Florida home"
                  width={600}
                  height={450}
                  className="w-full h-auto object-cover"
                  priority
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Detailed Content Section */}
      <section className="py-20 bg-white">
        <div className="max-w-4xl mx-auto px-4">
          <span className="inline-block text-sm font-semibold text-palm-600 uppercase tracking-wider mb-3">About Impact Doors</span>
          <h2 className="text-3xl md:text-4xl font-bold font-display text-gray-900 mb-8">
            Hurricane-Rated Doors Built for the South Florida Lifestyle
          </h2>

          <div className="prose prose-lg max-w-none text-gray-600 space-y-6">
            <p>
              Doors represent some of the largest and most vulnerable openings in any South Florida home. When a hurricane strikes, unprotected doors can blow in under extreme wind pressure, allowing rain, wind, and debris to devastate your interior. Impact doors are specifically engineered to resist these forces, combining reinforced frames with laminated impact glass that holds together even when struck by wind-borne debris traveling at over 100 miles per hour.
            </p>
            <p>
              At Florida Impact Windows & Doors, we install the complete range of impact door styles demanded by South Florida homeowners. Our most popular product is the impact sliding glass door, which is essential for the lanai, patio, and pool-deck living that defines life in Miami, Fort Lauderdale, and the Palm Beaches. We also install impact French doors for formal living and dining areas, impact entry doors that make a stunning first impression, and impact patio doors designed for seamless indoor-outdoor transitions.
            </p>
            <p>
              Every impact door installation begins with precise measurements taken at your home by our experienced project managers. Because doors bear significant structural and wind loads, proper sizing and installation are critical. Our certified installers use manufacturer-specified fasteners, anchoring systems, and waterproofing techniques to ensure every door performs as designed during a hurricane. We then coordinate all necessary permits and inspections with your local building department so you receive full code compliance documentation.
            </p>
            <p>
              The aesthetic options available in today&apos;s impact doors are remarkable. Modern manufacturing techniques allow for ultra-slim frame profiles that maximize glass area and views, premium powder-coat finishes in dozens of colors, decorative glass options for entry doors, and hardware packages ranging from minimalist contemporary to classic coastal. Whether your South Florida home is a modern waterfront estate in Miami Beach, a Mediterranean-style villa in Coral Gables, or a coastal cottage in Delray Beach, there is an impact door design that will elevate your home&apos;s beauty while delivering full hurricane protection.
            </p>
            <p>
              Beyond storm protection, impact doors deliver substantial daily benefits. The laminated glass significantly reduces outside noise, a real advantage in busy South Florida neighborhoods near airports, highways, and commercial districts. The Low-E coatings reflect solar heat, keeping your home cooler and reducing the workload on your air conditioning system. And the impact-rated glass plus multi-point locking hardware provide a formidable barrier against break-ins, giving your family added peace of mind every night.
            </p>
          </div>
        </div>
      </section>

      {/* Benefits Grid */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-16">
            <span className="inline-block text-sm font-semibold text-palm-600 uppercase tracking-wider mb-3">Key Benefits</span>
            <h2 className="text-3xl md:text-4xl font-bold font-display text-gray-900 mb-4">
              Advantages of Impact Doors for Your South Florida Home
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Impact doors combine beauty, performance, and protection in a single product that enhances your home every day.
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {benefits.map((benefit) => (
              <div
                key={benefit.title}
                className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-md transition-shadow"
              >
                <span className="text-4xl mb-4 block">{benefit.icon}</span>
                <h3 className="text-xl font-bold text-gray-900 mb-3 font-display">{benefit.title}</h3>
                <p className="text-gray-600 leading-relaxed">{benefit.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Why Choose Florida Impact Windows & Doors */}
      <section className="py-20 bg-ocean-950 relative overflow-hidden">
        <div className="absolute inset-0 bg-grid opacity-30" />
        <div className="absolute inset-0 mesh-gradient" />
        <div className="relative z-10 max-w-7xl mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div>
              <span className="inline-block text-sm font-semibold text-palm-400 uppercase tracking-wider mb-3">Why Choose Us</span>
              <h2 className="text-3xl md:text-4xl font-bold font-display text-white mb-6">
                South Florida&apos;s Trusted Impact Door Installers
              </h2>
              <p className="text-gray-400 mb-8 leading-relaxed">
                Florida Impact Windows & Doors brings specialized expertise to every impact door installation. Doors require precision fitting and structural anchoring that only experienced professionals can deliver reliably.
              </p>
              <ul className="space-y-4">
                {[
                  "Expert measurement and custom ordering for perfect fit",
                  "Factory-trained installers for PGT, CGI, ES, and CWS doors",
                  "Proper structural anchoring and waterproofing at every opening",
                  "Complete permit handling for Miami-Dade, Broward, and Palm Beach",
                  "Multi-point locking hardware installation and adjustment",
                  "Comprehensive cleanup and debris removal after installation",
                  "Manufacturer warranty registration and documentation",
                  "Post-installation support and hardware adjustment service",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-3">
                    <svg className="w-5 h-5 text-palm-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                    <span className="text-gray-300">{item}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-white/5 backdrop-blur-sm rounded-2xl p-10 border border-white/10">
              <h3 className="text-2xl font-bold text-white mb-6 font-display">Get a Free Door Consultation</h3>
              <p className="text-gray-400 mb-8">
                Our door specialists will visit your home, evaluate your existing doors, and recommend the ideal impact door solutions for your needs and budget.
              </p>
              <Link
                href="/get-estimate/"
                className="block w-full text-center bg-gradient-to-r from-palm-500 to-palm-600 text-white px-8 py-4 rounded-full font-bold text-lg hover:from-palm-600 hover:to-palm-700 transition-all shadow-lg shadow-palm-500/25"
              >
                Schedule Free Consultation
              </Link>
              <p className="text-center text-gray-500 text-sm mt-4">No obligation. No pressure. No cost.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Door Types */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-12">
            <span className="inline-block text-sm font-semibold text-ocean-600 uppercase tracking-wider mb-3">Door Styles</span>
            <h2 className="text-3xl md:text-4xl font-bold font-display text-gray-900 mb-4">
              Impact Door Types We Install
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              From grand entry doors to expansive sliding glass panels, we install every style of impact door for South Florida homes.
            </p>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {doorTypes.map((type) => (
              <Link
                key={type.name}
                href={type.href}
                className="flex items-center gap-3 p-5 rounded-2xl border border-gray-200 hover:border-ocean-300 hover:bg-ocean-50 transition-all group bg-white shadow-sm"
              >
                <div className="w-10 h-10 rounded-lg bg-ocean-100 flex items-center justify-center group-hover:bg-ocean-200 transition-colors flex-shrink-0">
                  <svg className="w-5 h-5 text-ocean-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 3h7v18H3zM14 12h.01" /><rect x="3" y="3" width="14" height="18" rx="1" strokeWidth={1.5} /></svg>
                </div>
                <span className="font-medium text-gray-700 group-hover:text-ocean-700 transition-colors">{type.name}</span>
              </Link>
            ))}
          </div>
          <div className="text-center mt-8">
            <Link href="/services/impact-windows/" className="inline-flex items-center gap-2 text-palm-600 font-semibold hover:text-palm-700 transition-colors">
              Also explore our Impact Windows
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" /></svg>
            </Link>
          </div>
        </div>
      </section>

      {/* Service Areas */}
      <ServiceAreaLinks
        serviceSlug="impact-doors"
        title="Impact Door Installation Throughout South Florida"
        subtitle="From oceanfront condos in Miami Beach to lakeside estates in Wellington, we install impact doors across the entire tri-county region."
        counties={[
          { county: "Miami-Dade County", cities: ["Miami", "Miami Beach", "Coral Gables", "Hialeah", "Doral", "Aventura", "Key Biscayne", "Pinecrest"], href: "/areas/miami/" },
          { county: "Broward County", cities: ["Fort Lauderdale", "Hollywood", "Pembroke Pines", "Weston", "Coral Springs", "Plantation", "Parkland", "Davie"], href: "/areas/fort-lauderdale/" },
          { county: "Palm Beach County", cities: ["West Palm Beach", "Boca Raton", "Delray Beach", "Jupiter", "Palm Beach Gardens", "Wellington", "Boynton Beach", "Lake Worth"], href: "/areas/west-palm-beach/" },
        ]}
      />

      {/* FAQ Section */}
      <section className="py-20 bg-white">
        <div className="max-w-4xl mx-auto px-4">
          <div className="text-center mb-12">
            <span className="inline-block text-sm font-semibold text-palm-600 uppercase tracking-wider mb-3">FAQ</span>
            <h2 className="text-3xl md:text-4xl font-bold font-display text-gray-900 mb-4">
              Frequently Asked Questions About Impact Doors
            </h2>
          </div>
          <div className="space-y-6">
            {faqs.map((faq) => (
              <div key={faq.question} className="bg-gray-50 rounded-2xl p-8 border border-gray-100">
                <h3 className="text-lg font-bold text-gray-900 mb-3 font-display">{faq.question}</h3>
                <p className="text-gray-600 leading-relaxed">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="py-20 bg-ocean-950 relative overflow-hidden">
        <div className="absolute inset-0 bg-grid opacity-30" />
        <div className="absolute inset-0 mesh-gradient" />
        <div className="relative z-10 max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-5xl font-bold font-display text-white mb-6">
            Upgrade to Impact Doors Today
          </h2>
          <p className="text-lg text-gray-300 mb-8 max-w-2xl mx-auto">
            Protect your family, enhance your home, and enjoy South Florida living at its finest. Schedule your free in-home impact door consultation now.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/get-estimate/"
              className="inline-flex items-center gap-2 bg-gradient-to-r from-palm-500 to-palm-600 text-white px-10 py-5 rounded-full font-bold text-lg hover:from-palm-600 hover:to-palm-700 transition-all shadow-lg shadow-palm-500/25 hover:shadow-palm-500/40"
            >
              Get Your Free Estimate
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" /></svg>
            </Link>
            <a
              href="tel:+17546004876"
              className="inline-flex items-center gap-2 text-white font-semibold text-lg hover:text-palm-300 transition-colors"
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" /></svg>
              Or Call (754) 600-4876
            </a>
          </div>
        </div>
      </section>
    </>
  );
}
